## 4.2. Veri Temizligi: 2. Kayip Degerler - Odev

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Veri kümesinde yer alan değişkenlerinin tiplerini ve her bir değişkenin eksik (null) değer oranını bulun.

states = pd.read_csv('states_all.csv')
states.info()
states.isnull().sum()/states.shape[0]*100

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1715 entries, 0 to 1714
Data columns (total 25 columns):
PRIMARY_KEY                     1715 non-null object
STATE                           1715 non-null object
YEAR                            1715 non-null int64
ENROLL                          1224 non-null float64
TOTAL_REVENUE                   1275 non-null float64
FEDERAL_REVENUE                 1275 non-null float64
STATE_REVENUE                   1275 non-null float64
LOCAL_REVENUE                   1275 non-null float64
TOTAL_EXPENDITURE               1275 non-null float64
INSTRUCTION_EXPENDITURE         1275 non-null float64
SUPPORT_SERVICES_EXPENDITURE    1275 non-null float64
OTHER_EXPENDITURE               1224 non-null float64
CAPITAL_OUTLAY_EXPENDITURE      1275 non-null float64
GRADES_PK_G                     1542 non-null float64
GRADES_KG_G                     1632 non-null float64
GRADES_4_G                      1632 non-null float64
GRADES_8_G                      1632 non-null float64
GRADES_12_G                     1632 non-null float64
GRADES_1_8_G                    1020 non-null float64
GRADES_9_12_G                   1071 non-null float64
GRADES_ALL_G                    1632 non-null float64
AVG_MATH_4_SCORE                565 non-null float64
AVG_MATH_8_SCORE                602 non-null float64
AVG_READING_4_SCORE             650 non-null float64
AVG_READING_8_SCORE             562 non-null float64
dtypes: float64(22), int64(1), object(2)
memory usage: 335.0+ KB

PRIMARY_KEY                      0.000000
STATE                            0.000000
YEAR                             0.000000
ENROLL                          28.629738
TOTAL_REVENUE                   25.655977
FEDERAL_REVENUE                 25.655977
STATE_REVENUE                   25.655977
LOCAL_REVENUE                   25.655977
TOTAL_EXPENDITURE               25.655977
INSTRUCTION_EXPENDITURE         25.655977
SUPPORT_SERVICES_EXPENDITURE    25.655977
OTHER_EXPENDITURE               28.629738
CAPITAL_OUTLAY_EXPENDITURE      25.655977
GRADES_PK_G                     10.087464
GRADES_KG_G                      4.839650
GRADES_4_G                       4.839650
GRADES_8_G                       4.839650
GRADES_12_G                      4.839650
GRADES_1_8_G                    40.524781
GRADES_9_12_G                   37.551020
GRADES_ALL_G                     4.839650
AVG_MATH_4_SCORE                67.055394
AVG_MATH_8_SCORE                64.897959
AVG_READING_4_SCORE             62.099125
AVG_READING_8_SCORE             67.230321
dtype: float64

In [3]:
states.head()

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,NaN,NaN,731634.0,208.0,252.0,207.0,NaN
1,1992_ALASKA,ALASKA,1992,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,NaN,NaN,122487.0,NaN,NaN,NaN,NaN
2,1992_ARIZONA,ARIZONA,1992,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,NaN,NaN,673477.0,215.0,265.0,209.0,NaN
3,1992_ARKANSAS,ARKANSAS,1992,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,NaN,NaN,441490.0,210.0,256.0,211.0,NaN
4,1992_CALIFORNIA,CALIFORNIA,1992,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,NaN,NaN,5254844.0,208.0,261.0,202.0,NaN

In [4]:
# Verimizde yıl (year) sütunu olduğunu farketmişsinizdir. Şimdilik yıl verisini unutun ve her bir gözlemin aynı 
# yıl içerisinde yapıldığını farz edin. Her bir değişken için eksik değerleri nasıl doldurabileceğinizi düşünün. 
# Eksik değerleri bir değerle doldurmak hangi değişkenler için anlamlı, hangileri için anlamsızdır?



# Bazi degiskenlerde eksik deger orani cok yuksek (ozellikle avg_math, avg_reading). Verinin turune ve yapacagimiz 
# analize gore belirli bir kabul limiti secilebilir. Bu soru icin GRADES_ALL_G sutunu uzerinden sorulari cevaplayacagim.

states['GRADES_ALL_G_N']=states['GRADES_ALL_G'].fillna(states['GRADES_ALL_G'].mean())

In [5]:
# Şimdi zaman faktörünü dikkate alma zamanı! 2. sorudaki cevabınızı tekrar gözden geçirin ve eksik verileri o yıl 
# içerisinde gözlemlenen değerlere dayanarak doldurun. 
# Örneğin, bir değeri ortalama değer ile doldurmak isterseniz, o yılın ortalamasını hesaplayın.

states['GRADES_ALL_G_Y'] = states['GRADES_ALL_G'].fillna(states.groupby('YEAR')['GRADES_ALL_G'].transform('mean'))

In [6]:
# Bu sefer, eksik değerleri enterpolasyon yaparak doldurun.

states['GRADES_ALL_G_INT'] = states['GRADES_ALL_G'].interpolate()

In [8]:
# İkinci, üçüncü ve dördüncü sorulardaki cevaplarınızı karşılaştırın. Anlamlı bir fark görebiliyor musunuz?

states[['GRADES_ALL_G_N','GRADES_ALL_G_Y','GRADES_ALL_G_INT']].describe()

# Asagidaki kodlarda da gorecegimiz uzere her bir yil icin ortalama deger alip kayip degerleri doldurdugumuz yontemde
# halen daha kayip degerlerimiz oldugunu goruyoruz. Bunun sebebi de 2019 yilinda hic bir mevcut veri olmamasi. 

# Bunun disinda, asagidaki 1. ve 3. sutunlarda gorecegimiz gibi, iki farkli yontemde ortalama ve standart sapma 
# degerlerinde farkliliklar oldu.

       GRADES_ALL_G_N  GRADES_ALL_G_Y  GRADES_ALL_G_INT
count    1.715000e+03    1.662000e+03      1.715000e+03
mean     9.139695e+05    9.142853e+05      8.742983e+05
std      1.030010e+06    1.046343e+06      1.044932e+06
min      6.844900e+04    6.844900e+04      6.844900e+04
25%      2.800010e+05    2.675600e+05      1.892720e+05
50%      6.809780e+05    6.584575e+05      5.970960e+05
75%      1.002840e+06    1.031506e+06      1.002840e+06
max      6.441557e+06    6.441557e+06      6.441557e+06

In [9]:
states.isnull().sum()/states.shape[0]*100

PRIMARY_KEY                      0.000000
STATE                            0.000000
YEAR                             0.000000
ENROLL                          28.629738
TOTAL_REVENUE                   25.655977
FEDERAL_REVENUE                 25.655977
STATE_REVENUE                   25.655977
LOCAL_REVENUE                   25.655977
TOTAL_EXPENDITURE               25.655977
INSTRUCTION_EXPENDITURE         25.655977
SUPPORT_SERVICES_EXPENDITURE    25.655977
OTHER_EXPENDITURE               28.629738
CAPITAL_OUTLAY_EXPENDITURE      25.655977
GRADES_PK_G                     10.087464
GRADES_KG_G                      4.839650
GRADES_4_G                       4.839650
GRADES_8_G                       4.839650
GRADES_12_G                      4.839650
GRADES_1_8_G                    40.524781
GRADES_9_12_G                   37.551020
GRADES_ALL_G                     4.839650
AVG_MATH_4_SCORE                67.055394
AVG_MATH_8_SCORE                64.897959
AVG_READING_4_SCORE             62.099125
AVG_READING_8_SCORE             67.230321
GRADES_ALL_G_N                   0.000000
GRADES_ALL_G_Y                   3.090379
GRADES_ALL_G_INT                 0.000000
dtype: float64

In [10]:
states.set_index("YEAR").isnull().groupby(level=0).mean()

,PRIMARY_KEY,STATE,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,SUPPORT_SERVICES_EXPENDITURE,...,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE,GRADES_ALL_G_N,GRADES_ALL_G_Y,GRADES_ALL_G_INT
YEAR,,,,,,,,,,,,,,,,,,,,,
1986,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
1987,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
1988,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
1989,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
1990,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.037736,0.981132,0.264151,1.000000,1.000000,0.0,0.0,0.0
1991,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
1992,0.0,0.0,1.000000,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,1.000000,1.000000,0.037736,0.188679,0.188679,0.188679,0.981132,0.0,0.0,0.0
1993,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
1994,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,1.000000,1.000000,0.037736,1.000000,1.000000,0.226415,0.981132,0.0,0.0,0.0
1995,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
1996,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,1.000000,1.000000,0.037736,0.981132,0.981132,1.000000,1.000000,0.0,0.0,0.0
1997,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
1998,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,0.037736,0.037736,0.037736,1.000000,1.000000,0.207547,0.264151,0.0,0.0,0.0
1999,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
2000,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,0.037736,0.037736,0.037736,0.188679,0.207547,0.981132,1.000000,0.0,0.0,0.0
2001,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
2002,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,0.037736,0.037736,0.037736,1.000000,1.000000,0.132075,0.169811,0.0,0.0,0.0
2003,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,0.037736,0.037736,0.037736,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2004,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
2005,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,0.037736,0.037736,0.037736,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2006,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
2007,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,0.037736,0.037736,0.037736,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2008,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
2009,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,0.037736,0.037736,0.037736,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2010,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
2011,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,0.037736,0.037736,0.037736,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2012,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
2013,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,0.037736,0.037736,0.037736,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2014,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
2015,0.0,0.0,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,0.037736,...,0.037736,0.037736,0.037736,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2016,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0
2017,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,0.037736,0.037736,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2019,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.0,0.0